# for general ------------------

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']


# You can confirm filetype by ':set filetype' command.
# plugin for linter
[[plugins]]
repo = 'w0rp/ale'
on_ft = ['go', 'haskell', 'python', 'java', 'tex', 'markdown', 'yaml', 'javascript', 'sql', 'html', 'elm']
hook_source = '''
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_open_list = 0
let g:ale_keep_list_window_open = 0

let g:ale_sign_error = '⨉'
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']

function! LinterStatus() abort
\ let l:counts = ale#statusline#Count(bufnr(''))
\ let l:all_errors = l:counts.error + l:counts.style_error
\ let l:all_non_errors = l:counts.total - l:all_errors
\ return l:counts.total == 0 ? 'OK' : printf(
\    '%dW %dE',
\    all_non_errors,
\    all_errors
\ )
endfunction

set statusline=%{LinterStatus()}

let g:ale_echo_msg_error_str = '⨉'
let g:ale_echo_msg_warning_str = '⚠'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

" moving between errors
nmap <silent> <C-n> <Plug>(ale_previous_wrap)
nmap <silent> <C-p> <Plug>(ale_next_wrap)

let g:ale_linters = {
\   'go':['gofmt', 'golint', 'go vet'],
\   'haskell': ['hlint'],
\   'python': ['flake8'],
\   'java': ['checkstyle'],
\   'tex': ['alex', 'proselint'],
\   'markdown': ['vale', 'proselint'],
\   'yaml': ['swaglint'],
\   'javascript':['eslint', 'flow'],
\   'sql':['sqlint'],
\   'html':['alex', 'proselint'],
\   'elm':['elm-format'],
\}
'''

# for ctags ------------------

[[plugins]]
repo = 'craigemery/vim-autotag'
on_ft = ['haskell', 'python', 'java', 'kotlin', 'tex', 'c']
hook_source = '''
let g:autotagTagsFile = 'tags'
let g:tagbar_autoshowtag = 1
let g:tagbar_show_visibility = 1
let g:tagbar_autopreview = 1
let g:tagbar_type_tex = {
\ 'ctagstype' : 'latex',
\ 'kinds' : [
\   'c:chapter:0:1',
\   's:section:0:1',
\   't:subsection:1:1',
\   'u:subsubsection:1:1',
\   'l:label:1:1'
\ ],
\ 'kind2scope' : {
\   'c' : 'chapter',
\   's' : 'section',
\   't' : 'subsection',
\   'u' : 'subsubsection',
\ },
\ 'scope2kind' : {
\   'chapter'  : 'c',
\   'section'  : 's',
\   'subsection': 't',
\   'subsubsection': 'u',
\  },
\ 'sort'    : 0,
\ }
let g:tagbar_type_haskell = {
\ 'ctagsbin'  : 'hasktags',
\ 'ctagsargs' : '-x -c -o-',
\ 'kinds'     : [
\    'm:modules:0:1',
\    'd:data: 0:1',
\    'd_gadt: data gadt:0:1',
\    't:type names:0:1',
\    'nt:new types:0:1',
\    'c:classes:0:1',
\    'cons:constructors:1:1',
\    'c_gadt:constructor gadt:1:1',
\    'c_a:constructor accessors:1:1',
\    'ft:function types:1:1',
\    'fi:function implementations:0:1',
\    'o:others:0:1'
\ ],
\ 'sro'        : '.',
\ 'kind2scope' : {
\   'm' : 'module',
\   'c' : 'class',
\   'd' : 'data',
\   't' : 'type'
\ },
\ 'scope2kind' : {
\   'module' : 'm',
\   'class'  : 'c',
\   'data'   : 'd',
\   'type'   : 't'
\ }
\ }
'''

[[plugins]]
repo = 'jstemmer/gotags'
on_ft = 'go'
hook_source = '''
let g:tagbar_type_go = {
\ 'ctagstype' : 'go',
\ 'kinds'     : [
\   'p:package',
\   'i:imports:1',
\   'c:constants',
\   'v:variables',
\   't:types',
\   'n:interfaces',
\   'w:fields',
\   'e:embedded',
\   'm:methods',
\   'r:constructor',
\   'f:functions'
\ ],
\ 'sro' : '.',
\ 'kind2scope' : {
\   't' : 'ctype',
\   'n' : 'ntype'
\ },
\ 'scope2kind' : {
\   'ctype' : 't',
\   'ntype' : 'n'
\ },
\ 'ctagsbin'  : 'gotags',
\ 'ctagsargs' : '-sort -silent'
\ }
'''

[[plugins]]
repo = 'majutsushi/tagbar'  # gd is command for 'go to definition'
on_ft = ['go', 'haskell', 'python', 'tex', 'markdown', 'terraform', 'yaml.ansible', 'make']
hook_source = '''
nmap <F8> :TagbarToggle<CR>
let g:tagbar_width = 30
let g:tagbar_autoshowtag = 1
let g:tagbar_type_ansible = {  
    \ 'ctagstype' : 'ansible',
    \ 'kinds' : [
    \ 't:tasks',
    \ 'h:hosts'
    \ ],
    \ 'sort' : 0
    \ }

let g:tagbar_type_terraform = {  
    \ 'ctagstype' : 'terraform',
    \ 'kinds' : [
    \ 'r:resources',
    \ 'm:modules',
    \ 'o:outputs',
    \ 'v:variables',
    \ 'f:tfvars'
    \ ],
    \ 'sort' : 0
    \ }

let g:tagbar_type_make = {  
    \ 'kinds':[
    \ 'm:macros',
    \ 't:targets'
    \ ]
    \}

let g:tagbar_type_markdown = {  
    \ 'ctagstype' : 'markdown',
    \ 'kinds' : [
    \ 'h:Heading_L1',
    \ 'i:Heading_L2',
    \ 'k:Heading_L3'
    \ ]
    \ }
'''

[[plugins]]
repo = 'airblade/vim-rooter'
on_ft = ['go', 'python']
hook_source = '''
let g:rooter_use_lcd = 1
let g:rooter_patterns = ['.git/', '.git', '.tags']
'''

# for golang ------------------

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
depends = ['deoplete.nvim']
build = 'make'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
let g:go_bin_path = $GOPATH.'/bin' 
filetype plugin indent on
'''

[[plugins]]
repo = 'sebdah/vim-delve'
on_ft = 'go'
hook_source = '''
let g:delve_enable_syntax_highlighting = 0
/let g:delve_backend = "native"
'''
hook_source = '''
nmap :bp :DlvToggleBreakpoint<CR> " <CR> means press Return key
nmap :tp :DlvToggleTracepoint<CR>
nmap :dlvdebug :DlvDebug<CR>
nmap :dlvtest :DlvTest<CR>
nmap :dlvclear :DlvClearAll<CR>
'''

[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = 'go'
hook_source = '''
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_auto_sameids = 1
'''

# for latex ------------------

[[plugins]]
repo = 'poppyschmo/deoplete-latex'
on_ft = 'tex'

[[plugins]]
repo = 'lervag/vimtex'
hook_source='''
" compile
let g:vimtex_compiler_latexmk = {
\ 'background': 1,
\ 'build_dir': '',
\ 'continuous': 1,
\ 'options': [
\    '-pdfdvi', 
\    '-verbose',
\    '-file-line-error',
\    '-synctex=1',
\    '-interaction=nonstopmode',
\ ],
\}
" viewer
let g:latex_view_general_viewer = '/usr/bin/evince'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
let g:latex_view_method = 'general'
" fold
let g:latex_fold_parts = [
\ "appendix",
\ "frontmatter",
\ "mainmatter",
\ "backmatter",
\ ]
let g:latex_fold_sections = [
\ "part",
\ "chapter",
\ "section",
\ "subsection",
\ "subsubsection",
\ ]
let g:latex_fold_enabled = 1
let g:latex_fold_automatic = 1
let g:latex_fold_envs = 0
" ignore font warnings
let g:vimtex_imaps_enabled = 0
let g:Tex_IgnoredWarnings =
\"Underfull\n".
\"Overfull\n".
\"specifier changed to\n".
\"You have requested\n".
\"Missing number, treated as zero.\n".
\"There were undefined references\n".
\"Citation %.%# undefined\n".
\"LaTeX Font Warning:"
let g:Tex_IgnoreLevel = 8
'''
on_ft = 'tex'

# for zsh ------------------
[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = 'zsh'

# for docker ------------------
[[plugins]]
repo = 'zchee/deoplete-docker'
on_ft = 'dockerfile'

# for plantuml ------------------
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'uml'

# for markdown ------------------
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'
[[plugins]]
repo = 'rhysd/vim-grammarous'
on_ft = 'markdown'
[[plugins]]
repo = 'kannokanno/previm'
hook_source='''
  let g:previm_open_cmd = 'google-chrome-stable'
'''
on_ft = 'markdown'

# for terraform ------------------
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'

# for ansible ------------------
[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = 'yaml.ansible'
hook_source = '''
  let g:ansible_unindent_after_newline = 1
  let g:ansible_attribute_highlight = "ob"
'''

# for toml ------------------
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# for python ------------------
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

# for ruby ------------------
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'

# for haskell ------------------
[[plugins]]
repo = 'neovimhaskell/neovim-ghcmod'
on_ft = 'haskell'

[[plugins]]
repo = 'bitc/lushtags'
on_ft = 'haskell'

# for rust ------------------
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = [ 'rust' ]
hook_source = '''
let g:rustfmt_autosave = 1
let g:rust_doc#define_map_K = 0
'''

repo = 'sebastianmarkow/deoplete-rust'
on_ft = [ 'rust' ]
depends = [ 'deoplete.nvim' ]

hook_source = '''
let g:deoplete#sources#rust#racer_binary='~/.cargo/bin/racer'
let g:deoplete#sources#rust#rust_source_path='~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src'
let $RUST_SRC_PATH='~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src'
let g:deoplete#sources#rust#show_duplicates=1
let g:deoplete#sources#rust#disable_keymap=1
nmap <buffer> gd <plug>DeopleteRustGoToDefinitionDefault
nmap <buffer> K  <plug>DeopleteRustShowDocumentation
'''

repo = 'racer-rust/vim-racer'
on_ft = [ 'rust' ]
hook_source = '''
set hidden
let g:racer_cmd = '~/.cargo/bin/racer'
let $RUST_SRC_PATH='~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src'
'''
